import { jsonCodec } from "../shared/json-codec.js";
const packageName = 'dsh-rollback-plugin';
function parameter(name) {
    return { name, wire: name, source: 'json', codec: jsonCodec('dsh-rollback-plugin#JsonValue') };
}
/** Consumer-side contribution; mirrors the Host descriptors in ../host/typert.ts. */
export const ROLLBACK_REMOTE = {
    package: packageName,
    descriptors: [
        {
            id: `${packageName}#rollback/prepare`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'prepare',
            invocation: { kind: 'direct' },
            parameters: [parameter('sessionId'), parameter('messageId')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/execute`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'execute',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/openAt`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'openAt',
            invocation: { kind: 'direct' },
            parameters: [parameter('sessionId'), parameter('path'), parameter('line')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/status`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'status',
            invocation: { kind: 'direct' },
            parameters: [parameter('sessionId')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/prepareTurn`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'prepareTurn',
            invocation: { kind: 'direct' },
            parameters: [parameter('sessionId'), parameter('turn')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/acceptAll`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'acceptAll',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/undoAll`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'undoAll',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/sessionChanges`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'sessionChanges',
            invocation: { kind: 'direct' },
            parameters: [parameter('sessionId')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/acceptFile`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'acceptFile',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/acceptModification`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'acceptModification',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/undoFile`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'undoFile',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
        {
            id: `${packageName}#rollback/undoModification`,
            service: 'rollback',
            namespace: 'rollback',
            method: 'undoModification',
            invocation: { kind: 'direct' },
            parameters: [parameter('request')],
            cancellation: { parameter: 'signal' },
            result: jsonCodec('dsh-rollback-plugin#RemoteResult'),
        },
    ],
};
export default ROLLBACK_REMOTE;
